version: '{build}'

image: Visual Studio 2017

branches:
    only:
        - /^(master|[1-9][0-9]*\.[1-9][0-9]*\.[1-9][0-9]*(-.+)?)$/

pull_requests:
    do_not_increment_build_number: true

environment:
    BUILD: $(APPVEYOR_BUILD_NUMBER)
    NUGET_API_KEY:
        secure: caOlzCKYY1Jw08B9EfPx5jBmyKxQ484KQI4eIaV18ThSFYnWkbtdedby4I9Eyxv4
    GITHUB_TOKEN:
        secure: IulXujun1RiFyQC2SrK5F/2MtGblamfSjQlGd62zphUlEV7TttNKJErPq6plSCD1

build_script:
    - cmd: ./build.cmd

nuget:
    disable_publish_on_pr: true

test: off

artifacts:
    - path: .\artifacts\*\*

deploy_script:
    - ps: .\tools\deploy.ps1